
name: UI Check Workflows

on: 
  pull_request:
    paths: 'actions/ui-check/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run sanity checks on tests
      run: npm run check:ui:test
      working-directory: actions/ui-check
