
name: UI Check Workflows

on: 
  pull_request:
    paths: 'actions/ui-check/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run sanity checks on ui tests
      run: npm run test:e2e:sanity
      working-directory: actions/ui-check
