
name: UI Check Workflows

on: 
  pull_request:
    paths: 'actions/ui-check/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run sanity checks on tests
      run: |
        ls -al
        npm run test:e2e:sanity
      working-directory: actions/ui-check
